name: Download, Split and Push 90MB Parts                       # name of workflow

on:
  workflow_dispatch:                                            # run with "workflow botton"
    inputs:                                                     # user input's
      file_url:
        description: 'لینک مستقیم فایل برای دانلود'
        required: true                                          # neceserry or not
        type: string
      foldername:
        description: 'نام فولدر خروجی ذخیره ی فایل تکه شده'
        required: true
        type: string

jobs:
  split-and-push:                                               # name of job 1
    runs-on: ubuntu-latest                                      # run on ubuntu last version
    permissions:
      contents: write                                           # let job push to repasitory
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4                               # clone repasitory to VM (virtual machine)

      - name: Create download directory
        run: mkdir -p ${{ inputs.foldername }}                  # -p (to refuse error)

      - name: Download file
        run: |                                                  # -z (to check filename)
          FILENAME="downloaded_file"
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV
          wget -O "${{ inputs.foldername }}/$FILENAME" "${{ inputs.file_url }}"

      - name: Split into 90MB parts
        run: |
          cd ${{ inputs.foldername }}
          split -b 90m "${{ env.FILENAME }}" "part_"
          rm "${{ env.FILENAME }}"
          cd ..

      - name: Commit and push parts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ inputs.foldername }}/part_*
          git commit -m "Add split parts (90MB each) from ${{ inputs.file_url }}" || echo "Nothing to commit"
          git push origin HEAD:main
